### ISSUE TITLE
Facebook exercise done

### ISSUE THREAD

**Issue by fwextensions** [fwextensions/ios-ybook#2]
@codepathreview, please review.

**Comment by timothy1ee** [comment]
You must be attending the class remotely? We're actually one week behind the schedule in the course portal. The homework this week was the Dropbox homework in Week 1. It's great that you were able to do the Facebook exercise though.

You should still go back and do the Dropbox exercise, there are a few concepts covered there that are different.

**Comment by fwextensions** [comment]
I was out sick on Thursday and you asked me to do the Facebook exercise.  I’m partway through the Dropbox app.

**Comment by timothy1ee** [comment]
Sorry for the confusion, the portal is off our schedule by one week. There was a Facebook exercise in the Week 1 exercises that we did in lab.
